version: '3.9'

services:
  
  hackathon-python:
    env_file:
      - dev.env
    image: hackathon/python
    volumes:
      - ./data:/service/data
    container_name: hackathon-python
    build:
      context: .
      dockerfile: ./Dockerfile_arm64 # change to Dockerfile on Linux
